security:
  basic:
    enabled: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lojugdemo
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: H2
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG